apiVersion: v1
kind: Service
metadata:
  name: ve-ctrl
spec:
  ports:
  - port: 7000
    protocol: TCP
    targetPort: 7000
    name: comm
  - port: 7777
    protocol: TCP
    targetPort: 7777
    name: http
  selector:
    run: ve-ctrl
  clusterIP: None